# Generated by Django 4.0.5 on 2022-06-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_review_created_at_review_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='names',
        ),
    ]
