# Generated by Django 4.0.5 on 2022-06-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='describtion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
