# Generated by Django 4.0.5 on 2022-06-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_color_color_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_str',
        ),
    ]
