# Generated by Django 4.0.5 on 2022-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='story',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
